---
title: "Class activity"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

# Data

Anxiety can affect musicians before performances, and can negatively affect their ability to play and their emotional state. In a [2010 study](https://journals.sagepub.com/doi/10.1177/1948550610370492), researchers examined anxiety in 37 undergraduate music majors. For each musician, data was collected on anxiety levels before different performances (between 2 and 15 performances were measured for each musician). Each row in the data represents one performance; in this lab, we will work with the following variables:

* `id`: a unique identifier for the musician
* `na`: negative affect score (a measure of anxiety)
* `large`: whether the musician was performing as part of a large ensemble (large = 1), or as part of a small ensemble or solo (large = 0)
* `audience`: who attended (Instructor, Public, Students, or Juried)


### Downloading the data

The following code imports the data and saves it as a data frame called `music`:

```r
music <- read.csv("https://sta279-s22.github.io/labs/music.csv")
```

## Initial model

The researchers hypothesize that audience type might impact performer anxiety, and that after accounting for audience type, students will be less anxious when performing in large ensembles. Furthermore, the researchers suspect that overall anxiety varies between individuals, but that the effects of audience and ensemble size (large vs. small) are the *same* for each individual

:::{.question}
#### Question 1

Write down a population mixed effects model that matches the researchers' hypotheses. Explain why your model captures each of the researchers' suspected effects. Remember to include distributions for the noise and random effect terms in your population model.

:::

:::{.question}
#### Question 2

Fit the model from Question 1, and report the estimated parameters (the $\beta$ s and the variance terms).
:::

:::{.question}
#### Question 3

Does the fitted model support the researchers' hypothesis that after accounting for audience type, students will be less anxious when performing in large ensembles? Explain your answer.
:::

:::{.question}
#### Question 4

Does the fitted model support the researchers' hypothesis that there is variability in anxiety between students? Calculate a statistic that supports your answer, and explain your reasoning.
:::


## Adding random slopes

Now researchers suspect that actually, the effects of audience and ensemble size (large vs. small) are *different* for each individual. To capture they additional variation, they will add a random slope to the model, so the effect of ensemble size can vary between students.

Here is the mixed effects model with the random slope:

$$Anxiety_{ij} = \beta_0 + \beta_1 Juried_{ij} + \beta_2 Public_{ij} + \beta_3 Student_{ij} + (\beta_4 + v_i) Large_{ij} + u_i + \varepsilon_{ij},$$

where $\begin{bmatrix} u_i \\ v_i \end{bmatrix} \sim N \left(\begin{bmatrix} 0 \\ 0 \end{bmatrix}, \begin{bmatrix} \sigma_u^2 & \rho \sigma_u \sigma_v \\ \rho \sigma_u \sigma_v & \sigma_v^2 \end{bmatrix} \right)$.

How should we interpret this?

* The intercept (i.e., the expected anxiety for student $i$ in a small, instructor-only performance) is $\beta_0 + u_i$. In other words, the overall anxiety level varies from student to student
* The coefficients for audience type ($\beta_1$, $\beta_2$, and $\beta_3$) are the *same* for all students. That is, the effect of audience type is the *same* for all students
* The coefficient for ensemble size ($\beta_4 + v_i$) depends on the student. Here $\beta_4$ describes the average effect of ensemble size. For example, if $\beta_4 < 0$, then students are less nervous performing in large ensembles than in small ensembles. The random slope $v_i$ tells us about the relative impact of ensemble size for student $i$. For example, if $\beta_4 < 0$ and $v_i < 0$, then student $i$ experiences a greater reduction in anxiety (in large ensembles) than the average student.
* The correlation $\rho$ describes the correlation between the random slope and the random intercept. E.g., if $\rho < 0$, then for students with a higher overall level of anxiety ($u_i$ big), performing in large ensembles reduces their anxiety more.

:::{.question}
#### Question 5

Use the following code to fit the mixed model with random slopes:

```{r, eval=F}
library(lme4)
m1 <- lmer(na ~ audience + large + (large|id), data = music)
summary(m1)
```

:::

:::{.question}
#### Question 6

Interpret the estimated parameters in the model.
:::

# Mixed model estimates

Consider the simple mixed model

$$Y_{ij} = \beta_0 + u_i + \beta_1 X_i + \varepsilon_{ij},$$

where $u_i \sim N(0, \sigma_u^2)$, $\varepsilon_{ij} \sim N(0, \sigma_\varepsilon^2)$, and $X_i \in \{0, 1\}$ with $X_1,...,X_{m_0} = 0$ and $X_{m_0 + 1},...,X_m = 1$. The estimated coefficients $\widehat{\beta}$ are given by

$$\widehat{\beta} = (X^T (ZGZ^T + R)^{-1} X)^{-1} X^T(ZGZ^T + R)^{-1} Y.$$

:::{.question}
#### Question 7

Derive $\widehat{\beta}_1$.
:::


