<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ciaran Evans">

<title>Class activity solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ca_lecture_19_solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="ca_lecture_19_solutions_files/libs/quarto-html/quarto.js"></script>
<script src="ca_lecture_19_solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="ca_lecture_19_solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ca_lecture_19_solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="ca_lecture_19_solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ca_lecture_19_solutions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ca_lecture_19_solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ca_lecture_19_solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ca_lecture_19_solutions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Class activity solutions</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ciaran Evans </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<ol type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"NMES1988"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>nmes <span class="ot">&lt;-</span> NMES1988 <span class="sc">|&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(visits, hospital, health, chronic, gender, school, insurance)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(visits <span class="sc">~</span> ., <span class="at">family =</span> poisson, <span class="at">data =</span> nmes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">lambda =</span> m1<span class="sc">$</span>fitted.values))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 46.71402</code></pre>
</div>
</div>
<p>The Poisson model only predicts about 47 0s, when really there are 683. Quite a big difference!</p>
<ol start="3" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(visits <span class="sc">~</span> ., <span class="at">data =</span> nmes)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = visits ~ ., data = nmes, init.theta = 1.206603534, 
    link = log)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      0.929257   0.054591  17.022  &lt; 2e-16 ***
hospital         0.217772   0.020176  10.793  &lt; 2e-16 ***
healthpoor       0.305013   0.048511   6.288 3.23e-10 ***
healthexcellent -0.341807   0.060924  -5.610 2.02e-08 ***
chronic          0.174916   0.012092  14.466  &lt; 2e-16 ***
gendermale      -0.126488   0.031216  -4.052 5.08e-05 ***
school           0.026815   0.004394   6.103 1.04e-09 ***
insuranceyes     0.224402   0.039464   5.686 1.30e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.2066) family taken to be 1)

    Null deviance: 5743.7  on 4405  degrees of freedom
Residual deviance: 5044.5  on 4398  degrees of freedom
AIC: 24359

Number of Fisher Scoring iterations: 1

              Theta:  1.2066 
          Std. Err.:  0.0336 

 2 x log-likelihood:  -24341.1070 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">size=</span><span class="fl">1.2066</span>, <span class="at">mu =</span> m2<span class="sc">$</span>fitted.values))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 608.0102</code></pre>
</div>
</div>
<p>The NB model predicts about 608 0s. Much closer to the truth, but perhaps still slightly underestimating.</p>
<ol start="4" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">hurdle</span>(visits <span class="sc">~</span> ., <span class="at">dist =</span> <span class="st">"poisson"</span>, <span class="at">zero.dist =</span> <span class="st">"binomial"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> nmes)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
hurdle(formula = visits ~ ., data = nmes, dist = "poisson", zero.dist = "binomial")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-5.4144 -1.1565 -0.4770  0.5432 25.0228 

Count model coefficients (truncated poisson with log link):
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      1.406459   0.024180  58.167  &lt; 2e-16 ***
hospital         0.158967   0.006061  26.228  &lt; 2e-16 ***
healthpoor       0.253521   0.017708  14.317  &lt; 2e-16 ***
healthexcellent -0.303677   0.031150  -9.749  &lt; 2e-16 ***
chronic          0.101720   0.004719  21.557  &lt; 2e-16 ***
gendermale      -0.062247   0.013055  -4.768 1.86e-06 ***
school           0.019078   0.001872  10.194  &lt; 2e-16 ***
insuranceyes     0.080879   0.017139   4.719 2.37e-06 ***
Zero hurdle model coefficients (binomial with logit link):
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      0.043147   0.139852   0.309 0.757688    
hospital         0.312449   0.091437   3.417 0.000633 ***
healthpoor      -0.008716   0.161024  -0.054 0.956833    
healthexcellent -0.289570   0.142682  -2.029 0.042409 *  
chronic          0.535213   0.045378  11.794  &lt; 2e-16 ***
gendermale      -0.415658   0.087608  -4.745 2.09e-06 ***
school           0.058541   0.011989   4.883 1.05e-06 ***
insuranceyes     0.747120   0.100880   7.406 1.30e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Number of iterations in BFGS optimization: 14 
Log-likelihood: -1.613e+04 on 16 Df</code></pre>
</div>
</div>
<p>In the hurdle model, <span class="math inline">\(p_i = P(Y_i &gt; 0)\)</span> (i.e., the probability of at least one physician visit). The coefficient on <code>school</code> is positive in the logistic component (0.058541), so individuals with more years of education are more likely to visit a physician at least once, holding other variables fixed.</p>
<ol start="5" type="1">
<li></li>
</ol>
<p>The coefficients of the count model give us information about individuals who visited a physician at least once (i.e., <span class="math inline">\(Y_i|(Y_i &gt; 0)\)</span>). In this case, the coefficient on <code>healthpoor</code> is positive (0.253521), so among individuals who visited a physician at least once, those with poor health tend to have more visits (holding other variables fixed).</p>
<ol start="6" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>X_count <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m3, <span class="st">"count"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>X_zero <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m3, <span class="st">"zero"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(m3, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">1</span>]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>lambda_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3, <span class="at">type=</span><span class="st">"count"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(<span class="fu">t</span>(X_zero) <span class="sc">%*%</span> <span class="fu">diag</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat)) <span class="sc">%*%</span> X_zero)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)      hospital    healthpoor healthexcellent
(Intercept)      0.0195586563 -8.410122e-04 -0.0033267457   -0.0019831551
hospital        -0.0008410122  8.360649e-03 -0.0012765937    0.0004082738
healthpoor      -0.0033267457 -1.276594e-03  0.0259287038    0.0011828756
healthexcellent -0.0019831551  4.082738e-04  0.0011828756    0.0203580983
chronic         -0.0021636421 -4.649426e-04 -0.0018121686    0.0008668868
gendermale      -0.0032177188 -3.752098e-04  0.0002268627   -0.0002057975
school          -0.0011527743  1.103794e-05  0.0001753575   -0.0001100645
insuranceyes    -0.0031817806  9.690135e-05  0.0015461375   -0.0001567760
                      chronic    gendermale        school  insuranceyes
(Intercept)     -2.163642e-03 -3.217719e-03 -1.152774e-03 -3.181781e-03
hospital        -4.649426e-04 -3.752098e-04  1.103794e-05  9.690135e-05
healthpoor      -1.812169e-03  2.268627e-04  1.753575e-04  1.546137e-03
healthexcellent  8.668868e-04 -2.057975e-04 -1.100645e-04 -1.567760e-04
chronic          2.059198e-03  1.518872e-05  1.822525e-05  9.237291e-05
gendermale       1.518872e-05  7.675187e-03  1.257930e-05 -5.606011e-04
school           1.822525e-05  1.257930e-05  1.437441e-04 -3.920903e-04
insuranceyes     9.237291e-05 -5.606011e-04 -3.920903e-04  1.017665e-02</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(m3, <span class="st">"zero"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)      hospital    healthpoor healthexcellent
(Intercept)      0.019558491 -8.409980e-04 -0.0033267422   -0.0019831848
hospital        -0.000840998  8.360642e-03 -0.0012765950    0.0004082750
healthpoor      -0.003326742 -1.276595e-03  0.0259287054    0.0011828785
healthexcellent -0.001983185  4.082750e-04  0.0011828785    0.0203580940
chronic         -0.002163609 -4.649428e-04 -0.0018121718    0.0008668891
gendermale      -0.003217739 -3.752095e-04  0.0002268659   -0.0002057992
school          -0.001152758  1.103627e-05  0.0001753575   -0.0001100611
insuranceyes    -0.003181772  9.690520e-05  0.0015461294   -0.0001567803
                      chronic    gendermale        school  insuranceyes
(Intercept)     -2.163609e-03 -3.217739e-03 -1.152758e-03 -3.181772e-03
hospital        -4.649428e-04 -3.752095e-04  1.103627e-05  9.690520e-05
healthpoor      -1.812172e-03  2.268659e-04  1.753575e-04  1.546129e-03
healthexcellent  8.668891e-04 -2.057992e-04 -1.100611e-04 -1.567803e-04
chronic          2.059194e-03  1.518872e-05  1.822147e-05  9.238207e-05
gendermale       1.518872e-05  7.675188e-03  1.258188e-05 -5.606087e-04
school           1.822147e-05  1.258188e-05  1.437425e-04 -3.920927e-04
insuranceyes     9.238207e-05 -5.606087e-04 -3.920927e-04  1.017667e-02</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(<span class="fu">t</span>(X_count) <span class="sc">%*%</span> <span class="fu">diag</span>(lambda_hat <span class="sc">*</span> <span class="fu">exp</span>(lambda_hat)<span class="sc">*</span>(<span class="sc">-</span>lambda_hat <span class="sc">+</span> <span class="fu">exp</span>(lambda_hat)<span class="sc">-</span> <span class="dv">1</span>) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                    <span class="sc">*</span> p_hat <span class="sc">/</span>((<span class="fu">exp</span>(lambda_hat) <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">%*%</span> X_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)      hospital    healthpoor healthexcellent
(Intercept)      5.899031e-04 -2.546829e-06 -6.392235e-05   -3.991325e-05
hospital        -2.546829e-06  3.521323e-05 -1.791974e-05    4.896721e-06
healthpoor      -6.392235e-05 -1.791974e-05  3.141508e-04    2.187940e-05
healthexcellent -3.991325e-05  4.896721e-06  2.187940e-05    9.779638e-04
chronic         -3.895624e-05 -5.471726e-06 -2.668451e-05    1.460936e-05
gendermale      -4.827838e-05 -1.171305e-06  1.915112e-06   -3.944388e-06
school          -3.048319e-05  2.115894e-07  3.937301e-06   -3.356241e-06
insuranceyes    -1.436547e-04 -4.337054e-06  2.539811e-05   -2.201073e-06
                      chronic    gendermale        school  insuranceyes
(Intercept)     -3.895624e-05 -4.827838e-05 -3.048319e-05 -1.436547e-04
hospital        -5.471726e-06 -1.171305e-06  2.115894e-07 -4.337054e-06
healthpoor      -2.668451e-05  1.915112e-06  3.937301e-06  2.539811e-05
healthexcellent  1.460936e-05 -3.944388e-06 -3.356241e-06 -2.201073e-06
chronic          2.153596e-05 -1.218524e-06  1.661337e-07  2.971209e-06
gendermale      -1.218524e-06  1.699687e-04 -3.181297e-07 -1.188030e-05
school           1.661337e-07 -3.181297e-07  3.458471e-06 -8.738299e-06
insuranceyes     2.971209e-06 -1.188030e-05 -8.738299e-06  2.867959e-04</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(m3, <span class="st">"count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)      hospital    healthpoor healthexcellent
(Intercept)      5.846517e-04 -2.233679e-06 -6.534266e-05   -3.553615e-05
hospital        -2.233679e-06  3.673579e-05 -1.681527e-05    5.128960e-06
healthpoor      -6.534266e-05 -1.681527e-05  3.135595e-04    2.223889e-05
healthexcellent -3.553615e-05  5.128960e-06  2.223889e-05    9.703390e-04
chronic         -4.044102e-05 -5.217719e-06 -2.667198e-05    1.478391e-05
gendermale      -4.591969e-05 -2.485459e-06  1.907794e-06   -4.617467e-06
school          -3.019630e-05  1.753925e-07  3.936283e-06   -4.052731e-06
insuranceyes    -1.391763e-04 -5.108786e-06  2.673641e-05    1.446040e-06
                      chronic    gendermale        school  insuranceyes
(Intercept)     -4.044102e-05 -4.591969e-05 -3.019630e-05 -1.391763e-04
hospital        -5.217719e-06 -2.485459e-06  1.753925e-07 -5.108786e-06
healthpoor      -2.667198e-05  1.907794e-06  3.936283e-06  2.673641e-05
healthexcellent  1.478391e-05 -4.617467e-06 -4.052731e-06  1.446040e-06
chronic          2.226601e-05 -1.100540e-06  2.134670e-07  2.472441e-06
gendermale      -1.100540e-06  1.704201e-04 -4.788865e-07 -1.254832e-05
school           2.134670e-07 -4.788865e-07  3.502854e-06 -9.612795e-06
insuranceyes     2.472441e-06 -1.254832e-05 -9.612795e-06  2.937352e-04</code></pre>
</div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>